import Head from 'next/head'
import Homee from './components/Homee'

export default function Home() {
  return (
    <>
      <Head>
        <title>Money Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>     
      <Homee />
    </>
  )
}
